import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>zundou</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          zundou
        </h1>

        <p className={styles.description}>
          制作物リンク
          <ul>
          <li>A</li>
          <li>B</li>
          <li>C</li>
          </ul>
        </p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
